# tint
# Autogenerated from man page /usr/share/man/man6/tint.6.gz
complete -c tint -s h -d 'Show summary of options'
complete -c tint -s l -d 'Specify the starting level (1-9)'
complete -c tint -s n -d 'Draw next shape'
complete -c tint -s d -d 'Draw dotted lines'
complete -c tint -s b -d 'Use the specified character (instead of spaces) to draw blocks'

